name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: NPM Install
        run: npm ci
        working-directory: ./src/frontend

      # - name: Test
      #   run: npm run test
      #   working-directory: ./src/frontend

      - name: Build
        run: npm run build
        working-directory: ./src/frontend